### ISSUE TITLE
Possible bug in linear algebra functions for LPDO with 4-site tensors

### ISSUE THREAD

**Issue by GTorlai** [GTorlai/PastaQ.jl#141] opened 2020-10-08 14:52 UTC
Functions to verify:
- [ ] `tr`
- [ ] `inner`
- [ ] `fidelity_bound`
- [ ] `frobenius_distance`
- [ ] `fullmatrix` (for `full_fidelity`)

From master:

```julia
using PastaQ
using Random
using ITensors

Random.seed!(1234)

N = 4
depth = 4
nshots = 100
gates = randomcircuit(N, depth)

data, Λ = getsamples(N, gates, nshots;
                     process = true,
                     noise = ("amplitude_damping", (γ = 0.01,)))

@show tr(Λ.M)
# 0.7852946862110146 - 1.2889900736434508e-16im

Λ_split = PastaQ.splitchoi(Λ)
@show tr(Λ_split.M)
# 16.000000000000053 + 3.0797721974420045e-15im (correct value of 2^N)

```

**Comment by mtfishman** [comment] 2020-10-08 16:48
Ok, I know what the problem is. For an MPO with multiple site indices, it is using a 4-index delta tensor, instead of two 2-index delta tensors. This needs to be fixed in ITensors.jl. Besides `tr(::MPO)`, did you see any other specific issues?

**Comment by GTorlai** [comment] 2020-10-08 16:50
I think that only other one is `inner`, which should have a similar fix.

**Comment by mtfishman** [comment] 2020-10-08 16:52
Could you give an example of where `inner` was failing? For example, which types weren't working with `inner`? I don't think `inner` should have the same kind of issue that `tr` is having.

**Comment by GTorlai** [comment] 2020-10-08 17:07
```julia
using PastaQ
using Random
using ITensors
Random.seed!(1234)
# Make the random circuit
N = 4
depth = 4
nshots = 10_000
gates = randomcircuit(N, depth)
# Generate samples
data, Φ = getsamples(N, gates, nshots;
                     process = true,
                     noise = ("amplitude_damping", (γ = 0.01,)))
N = length(Φ)
χ = 8
ξ = 2
# Initialize the Choi LPDO
Λ0 = randomprocess(Φ; mixed = true, χ = χ, ξ = ξ)
# Initialize stochastic gradient descent optimizer
opt = SGD(η = 0.1)
# Run process tomography
println("Run process tomography to learn noisy process Λ")
Λ = tomography(data, Λ0;
               optimizer = opt,
               batchsize = 500,
               epochs = 5,
               target = Φ)
Φ_mpo  = Φ.M
Λ_lpdo = Λ.M
normalize!(Φ_mpo)
normalize!(Λ_lpdo)
@show fidelity_bound(Φ_mpo,Λ_lpdo)

# Output:
# Run process tomography to learn noisy process Λ
# Ep = 1  Loss = 2.77860E+00  Trace distance = 1.770E+01  Fidelity bound = 4.072E-01  Time = 2.684 sec
# Ep = 2  Loss = 2.70687E+00  Trace distance = 1.767E+01  Fidelity bound = 1.031E+00  Time = 2.697 sec
# Ep = 3  Loss = 2.66224E+00  Trace distance = 1.761E+01  Fidelity bound = 2.072E+00  Time = 2.568 sec
# Ep = 4  Loss = 2.62129E+00  Trace distance = 1.752E+01  Fidelity bound = 3.732E+00  Time = 2.562 sec
# Ep = 5  Loss = 2.57854E+00  Trace distance = 1.739E+01  Fidelity bound = 6.026E+00  Time = 2.520 sec
# 
# fidelity_bound(Φ_mpo, Λ_lpdo) = 6.026397086852683
```

**Closed** 2020-10-08 21:17 UTC
Labels: bug
